spec-version: 0.36.0
name: spt-make-realism-patch
version: 0.1.0
license: BSD-3-Clause
license-file: LICENSE
author: Victor Nascimento Bakke <gipphe@gmail.com>
maintainer: Victor Nascimento Bakke <gipphe@gmail.com>
github: Gipphe/spt-make-realism-patch
category: SPT
extra-source-files:
  - CHANGELOG.md
  - README.md

synopsis: >
  Automatically create a Realism Mod patch from a set of item JSON files for
  SPT.

language: GHC2021

ghc-options:
  - -Weverything
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-kind-signatures
  - -Wno-unsafe
  - -Wno-monomorphism-restriction

default-extensions:
  - DerivingVia
  - DataKinds
  - DuplicateRecordFields
  - ImportQualifiedPost
  - LambdaCase
  - LinearTypes
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - StrictData

dependencies:
  - base
  - relude
  - aeson
  - text
  - optparse-applicative

executable:
  main: Main.hs
  source-dirs: app
  ghc-options:
    - -threaded
