{-# LANGUAGE TemplateHaskell #-}

-- | Generated by make-base-template
module SPT.Props
    ( Props (..)
    )
where

import Data.Aeson.TH
    ( defaultOptions
    , deriveFromJSON
    , fieldLabelModifier
    )
import Relude


data Props = MkProps
    { propsName :: Maybe Text
    , propsShortName :: Maybe Text
    , propsDescription :: Maybe Text
    , propsWeight :: Maybe Double
    , propsStackMaxSize :: Maybe Double
    , propsStackObjectsCount :: Maybe Double
    , propsNotShownInSlot :: Maybe Bool
    , propsExaminedByDefault :: Maybe Bool
    , propsExamineTime :: Maybe Double
    , propsIsUndiscardable :: Maybe Bool
    , propsIsUnsaleable :: Maybe Bool
    , propsIsUnbuyable :: Maybe Bool
    , propsIsUngivable :: Maybe Bool
    , propsIsLockedafterEquip :: Maybe Bool
    , propsQuestItem :: Maybe Bool
    , propsLootExperience :: Maybe Double
    , propsExamineExperience :: Maybe Double
    , propsHideEntrails :: Maybe Bool
    , propsRepairCost :: Maybe Double
    , propsRepairSpeed :: Maybe Double
    , propsExtraSizeLeft :: Maybe Double
    , propsExtraSizeRight :: Maybe Double
    , propsExtraSizeUp :: Maybe Double
    , propsExtraSizeDown :: Maybe Double
    , propsExtraSizeForceAdd :: Maybe Bool
    , propsMergesWithChildren :: Maybe Bool
    , propsCanSellOnRagfair :: Maybe Bool
    , propsCanRequireOnRagfair :: Maybe Bool
    , propsConflictingItems :: Maybe [Text]
    , propsUnlootable :: Maybe Bool
    , propsAnimationVariantsNumber :: Maybe Double
    , propsDiscardingBlock :: Maybe Bool
    , propsRagFairCommissionModifier :: Maybe Double
    , propsIsAlwaysAvailableForInsurance :: Maybe Bool
    , propsDiscardLimit :: Maybe Double
    , propsDropSoundType :: Maybe Text
    , propsCanPutIntoDuringTheRaid :: Maybe Bool
    , propsDurability :: Maybe Double
    , propsAccuracy :: Maybe Double
    , propsRecoil :: Maybe Double
    , propsLoudness :: Maybe Double
    , propsEffectiveDistance :: Maybe Double
    , propsErgonomics :: Maybe Double
    , propsVelocity :: Maybe Double
    , propsRaidModdable :: Maybe Bool
    , propsToolModdable :: Maybe Bool
    , propsBlocksFolding :: Maybe Bool
    , propsBlocksCollapsible :: Maybe Bool
    , propsIsAnimated :: Maybe Bool
    , propsHasShoulderContact :: Maybe Bool
    , propsSightingRange :: Maybe Double
    , propsDoubleActionAccuracyPenaltyMult :: Maybe Double
    , propsmuzzleModType :: Maybe Text
    , propsDurabilityBurnModificator :: Maybe Double
    , propsHeatFactor :: Maybe Double
    , propsCoolFactor :: Maybe Double
    }
    deriving stock (Show)


$(deriveFromJSON defaultOptions {fieldLabelModifier = drop 5} ''Props)
