{-# LANGUAGE TemplateHaskell #-}

-- | Generated by make-base-template
module SPT.Template
    ( Template (..)
    )
where

import Data.Aeson.TH
    ( defaultOptions
    , deriveFromJSON
    , fieldLabelModifier
    )
import Relude
import SPT.Props (Props)


data Template = MkTemplate
    { template_id :: Maybe Text
    , template_name :: Maybe Text
    , template_parent :: Maybe Text
    , template_proto :: Maybe Text
    , template_type :: Maybe Text
    , template_tpl :: Maybe Text
    , template_props :: Maybe Props
    }


$(deriveFromJSON defaultOptions {fieldLabelModifier = drop 8} ''Template)
