{-# LANGUAGE TemplateHaskell #-}

-- | Generated by make-snippets
module SPT.Realism.AmmoTemplate
    ( AmmoTemplate (..)
    )
where

import Data.Aeson.TH (deriveToJSON)
import Optics.TH (makeFieldLabels)
import Relude
import SPT.Realism.TH (derivingOpts)


data AmmoTemplate = MkAmmoTemplate
    { basePriceModifier :: Maybe Double
    , damage :: Maybe Double
    , itemID :: Text
    , loyaltyLevel :: Maybe Double
    , name :: Text
    , penetrationPower :: Maybe Double
    , templateType :: Maybe Text
    }
    deriving stock (Show)


$(deriveToJSON derivingOpts ''AmmoTemplate)


$(makeFieldLabels ''Ammo)
