{-# LANGUAGE TemplateHaskell #-}

-- | Generated by make-snippets
module SPT.Realism.GearTemplate
    ( GearTemplate (..)
    )
where

import Data.Aeson.TH (deriveToJSON)
import Relude
import SPT.Realism.TH (derivingOpts)


data GearTemplate = MkGearTemplate
    { allowADS :: Maybe Bool
    , armorClass :: Maybe Text
    , blocksMouth :: Maybe Bool
    , canSpall :: Maybe Bool
    , comfort :: Maybe Double
    , _dB :: Maybe Text
    , gasProtection :: Maybe Double
    , isGasMask :: Maybe Bool
    , itemID :: Text
    , _loyaltylevel :: Maybe Double
    , loyaltyLevel :: Maybe Double
    , maskToUse :: Maybe Text
    , _mousePenalty :: Maybe Double
    , name :: Text
    , price :: Maybe Double
    , radProtection :: Maybe Double
    , reloadSpeedMulti :: Maybe Double
    , spallReduction :: Maybe Double
    , _speedPenaltyPercent :: Maybe Double
    , templateID :: Maybe Text
    , templateType :: Maybe Text
    , _weaponErgonomicPenalty :: Maybe Double
    }


$(deriveToJSON derivingOpts ''GearTemplate)
