{-# LANGUAGE TemplateHaskell #-}

-- | Generated by make-snippets
module SPT.Realism.ModTemplate
    ( ModTemplate (..)
    )
where

import Data.Aeson.TH (deriveToJSON)
import Relude
import SPT.Realism.TH (derivingOpts)


data ModTemplate = MkModTemplate
    { accuracy :: Maybe Double
    , aimSpeed :: Maybe Double
    , autoROF :: Maybe Double
    , blocksFolding :: Maybe Bool
    , cameraRecoil :: Maybe Double
    , canCycleSubs :: Maybe Bool
    , centerOfImpact :: Maybe Double
    , chamberSpeed :: Maybe Double
    , checkTimeModifier :: Maybe Double
    , conflictingItems :: [Text]
    , convergence :: Maybe Double
    , coolFactor :: Maybe Double
    , dispersion :: Maybe Double
    , durabilityBurnModificator :: Maybe Double
    , ergonomics :: Maybe Double
    , fixSpeed :: Maybe Double
    , flash :: Maybe Double
    , hasShoulderContact :: Maybe Bool
    , heatFactor :: Maybe Double
    , horizontalRecoil :: Maybe Double
    , itemID :: Text
    , loadUnloadModifier :: Maybe Double
    , loudness :: Maybe Double
    , loyaltyLevel :: Maybe Double
    , magMalfunctionChance :: Maybe Double
    , meleeDamage :: Maybe Double
    , modMalfunctionChance :: Maybe Double
    , modType :: Maybe Text
    , name :: Text
    , price :: Maybe Double
    , recoilAngle :: Maybe Double
    , reloadSpeed :: Maybe Double
    , semiROF :: Maybe Double
    , shotgunDispersion :: Maybe Double
    , stockAllowADS :: Maybe Bool
    , templateID :: Maybe Text
    , templateType :: Maybe Text
    , velocity :: Maybe Double
    , verticalRecoil :: Maybe Double
    , weight :: Maybe Double
    }


$(deriveToJSON derivingOpts ''ModTemplate)
